/*
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
const { readFileSync, writeFileSync, existsSync, mkdirSync, rmSync } = require('fs');
const tar = require('tar');
const path = require('path');

function ensureDirSync(path) {
  !existsSync(path) && mkdirSync(path, { recursive: true });
}

function removeSync(path) {
  rmSync(path, { recursive: true, force: true });
}

const HEADER = `/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable quotes */
// file generated by ./scripts/updateRuntimeDependencies.js
`;

/**
 * Package the TypeScript declarations for dayjs and jsonpath.
 * These are needed at runtime to type-check user TypeScript code and template logic
 * against the dayjs / jsonpath libraries when compiling to JS.
 *
 * Note: the runtime SmartLegalContract declarations (TemplateLogic, EngineResponse,
 * etc.) are no longer bundled here. They are emitted directly by
 * TypeScriptCompilationContext with model-derived State/Request/Response/Event bounds
 * so that the class hierarchy is enforced at compile time.
 */
const dayjs = readFileSync('./node_modules/dayjs/index.d.ts').toString(
  'base64'
);
const jsonpath = readFileSync(
  './node_modules/@types/jsonpath/index.d.ts'
).toString('base64');

removeSync('./src/runtime/');
ensureDirSync('./src/runtime/');
writeFileSync(
  './src/runtime/declarations.ts',
  `
${HEADER}

export const DAYJS_BASE64 = '${dayjs}';
export const JSONPATH_BASE64 = '${jsonpath}';
`
);

/**
 * Package the TypeScript lib files that user code is compiled against in the browser,
 * so that the browser doesn't fetch them from the TypeScript CDN at runtime. This is
 * the ES2022 lib (the 'lib' compiler option in TypeScriptToJavaScriptCompiler) and every
 * lib file it references. The DOM and web worker libs are deliberately left out.
 */
const TYPESCRIPT_LIB_DIR = path.dirname(require.resolve('typescript/lib/lib.d.ts'));
const TYPESCRIPT_ROOT_LIB = 'lib.es2022.d.ts';
const typescriptLibs = {};
function addTypeScriptLib(fileName) {
  const key = `/${fileName}`;
  if (typescriptLibs[key] !== undefined) {
    return;
  }
  const contents = readFileSync(path.join(TYPESCRIPT_LIB_DIR, fileName), 'utf-8');
  typescriptLibs[key] = contents;
  for (const match of contents.matchAll(/\/\/\/\s*<reference\s+lib="([^"]+)"/g)) {
    addTypeScriptLib(`lib.${match[1].toLowerCase()}.d.ts`);
  }
}
addTypeScriptLib(TYPESCRIPT_ROOT_LIB);
const typescriptVersion = require('typescript/package.json').version;

writeFileSync(
  './src/runtime/typescriptLibs.ts',
  `
${HEADER}

export const TYPESCRIPT_LIBS_VERSION = '${typescriptVersion}';
export const TYPESCRIPT_LIBS: Record<string, string> = ${JSON.stringify(typescriptLibs)};
`
);
