/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Writes src/runtime/logicDeclarations.ts: the declarations of src/agreement/logic.ts, the
// logic API, as the engine supplies them to template logic when compiling it (as
// '@accordproject/template-engine/logic'). Run by prebuild; logic.ts is self-contained.
const { writeFileSync } = require('fs');
const path = require('path');
const ts = require('typescript');

const source = path.join(__dirname, '..', 'src', 'agreement', 'logic.ts');
const target = path.join(__dirname, '..', 'src', 'runtime', 'logicDeclarations.ts');

let declarations;
const program = ts.createProgram([source], {
    declaration: true,
    emitDeclarationOnly: true,
    removeComments: false,
    strict: true,
    target: ts.ScriptTarget.ES2021,
    skipLibCheck: true,
});
const result = program.emit(program.getSourceFile(source), (fileName, text) => {
    if (fileName.endsWith('.d.ts')) {
        declarations = text;
    }
});
const diagnostics = ts.getPreEmitDiagnostics(program).concat(result.diagnostics);
if (diagnostics.length > 0 || !declarations) {
    throw new Error(ts.formatDiagnostics(diagnostics, ts.createCompilerHost({})) || 'No declarations emitted.');
}

const HEADER = require('fs').readFileSync(__filename, 'utf8').split('\n').slice(0, 13).join('\n');
writeFileSync(target, `${HEADER}

/* eslint-disable quotes */
// file generated by ./scripts/updateLogicDeclarations.js from src/agreement/logic.ts

export const LOGIC_DECLARATIONS = ${JSON.stringify(declarations)};
`);
