"use strict";
/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LOGIC_MODULE = exports.TYPES_MODULE = void 0;
exports.typeFactories = typeFactories;
exports.enumValues = enumValues;
exports.typeValues = typeValues;
exports.typesSource = typesSource;
const logic_1 = require("./logic");
/** The module logic imports its factories from, relative to logic/logic.ts. */
exports.TYPES_MODULE = './generated/types';
/** The module logic imports the logic API from. */
exports.LOGIC_MODULE = '@accordproject/template-engine/logic';
function modelFiles(modelManager) {
    // System models (concerto@1.0.0) declare only abstract types.
    return modelManager.getModelFiles()
        .slice()
        .sort((a, b) => a.getNamespace().localeCompare(b.getNamespace()));
}
/**
 * Every concrete, non-enum class declaration in the models, as a factory, sorted by
 * namespace then name. Factories are exported by short name, so two declarations that
 * share one are an error.
 * @param {ModelManager} modelManager - the template's models
 * @returns {TypeFactory[]} the factories
 */
function typeFactories(modelManager) {
    const factories = [];
    const names = new Map();
    for (const modelFile of modelFiles(modelManager)) {
        const declarations = modelFile.getAllDeclarations()
            .filter((d) => d.isClassDeclaration?.() && !d.isEnum?.() && !d.isAbstract())
            .sort((a, b) => a.getName().localeCompare(b.getName()));
        for (const d of declarations) {
            const name = d.getName();
            const fqn = d.getFullyQualifiedName();
            if (names.has(name)) {
                throw new Error(`${fqn} and ${names.get(name)} have the same name, so logic can't import both from '${exports.TYPES_MODULE}'. Rename one of them.`);
            }
            names.set(name, fqn);
            const identifiedBy = d.isIdentified() && !d.isSystemIdentified() ? d.getIdentifierFieldName() : undefined;
            factories.push({ name, namespace: modelFile.getNamespace(), fqn, ...(identifiedBy ? { identifiedBy } : {}) });
        }
    }
    return factories;
}
/**
 * Every enum in the models, by namespace then name, as the object Concerto's TypeScript
 * codegen declares it (`enum E { A = 'A' }`).
 * @param {ModelManager} modelManager - the template's models
 * @returns {Record<string, Record<string, Record<string, string>>>} the enums
 */
function enumValues(modelManager) {
    const result = {};
    for (const modelFile of modelManager.getModelFiles(true)) {
        const enums = modelFile.getAllDeclarations().filter((d) => d.isEnum?.());
        for (const d of enums) {
            const values = Object.fromEntries(d.getOwnProperties().map((p) => [p.getName(), p.getName()]));
            (result[modelFile.getNamespace()] ??= {})[d.getName()] = Object.freeze(values);
        }
    }
    return result;
}
/**
 * The factories, as the values logic imports from './generated/types'.
 * @param {ModelManager} modelManager - the template's models
 * @returns {Record<string, ConceptType<IConcept>>} the factories, by name
 */
function typeValues(modelManager) {
    return Object.fromEntries(typeFactories(modelManager).map(f => [
        f.name,
        f.identifiedBy
            ? (0, logic_1.identifiedType)()(f.fqn, f.identifiedBy)
            : (0, logic_1.conceptType)()(f.fqn),
    ]));
}
/**
 * The TypeScript for logic/generated/types.ts: the factories, typed by the interfaces
 * Concerto's TypeScript codegen writes alongside it.
 * @param {ModelManager} modelManager - the template's models
 * @param {string} [logicModule] - where the factories' constructors are imported from
 * @returns {string} the module's source
 */
function typesSource(modelManager, logicModule = exports.LOGIC_MODULE) {
    const factories = typeFactories(modelManager);
    const byNamespace = new Map();
    for (const f of factories) {
        byNamespace.set(f.namespace, [...(byNamespace.get(f.namespace) ?? []), f]);
    }
    return [
        '// Generated by template-engine from the models: one factory per concrete type,',
        '// so logic never writes a $class by hand. Do not edit.',
        `import { conceptType, identifiedType } from '${logicModule}';`,
        ...[...byNamespace].map(([namespace, fs]) => `import type { ${fs.map(f => `I${f.name}`).join(', ')} } from './${namespace}';`),
        '',
        ...factories.map(f => f.identifiedBy
            ? `export const ${f.name} = identifiedType<I${f.name}>()('${f.fqn}', '${f.identifiedBy}');`
            : `export const ${f.name} = conceptType<I${f.name}>()('${f.fqn}');`),
        '',
    ].join('\n');
}
//# sourceMappingURL=types.js.map